name: Automated feedback
on:
  push:
    branches: [ main ]
jobs:
  build-with-setup-java-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: 12
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build --info